version: 2

sources:
  - name: silver_311
    description: "NYC 311 Silver Layer - Cleaned and standardized complaints"
    database: nyc_311_dev
    schema: silver
    
    tables:
      - name: silver_311
        description: "Production-ready 311 complaints with quality flags"
        
        freshness:
          warn_after: {count: 25, period: hour}
          error_after: {count: 30, period: hour}
        
        loaded_at_field: _unified_processed_timestamp
        
        columns:
          # Primary Key
          - name: unique_key
            data_tests:
              - unique
              - not_null
          
          # Temporal
          - name: created_date
            data_tests:
              - not_null
          
          - name: closed_date
            description: "Enriched with inference from resolution_action_updated_date"
          
          - name: closed_date_source
            data_tests:
              - accepted_values:
                  values: ['ORIGINAL', 'INFERRED_FROM_RESOLUTION', 'MISSING']
          
          # Core Dimensions
          - name: agency
            data_tests:
              - not_null
          
          - name: complaint_type
            data_tests:
              - not_null
          
          - name: status
            data_tests:
              - not_null
          
          - name: borough
            data_tests:
              - not_null
          
          # Quality Flags
          - name: is_closed
            data_tests:
              - not_null
          
          - name: has_valid_location
            data_tests:
              - not_null
          
          - name: has_invalid_closed_date
            data_tests:
              - not_null
          
          # Metadata
          - name: _unified_processed_timestamp
            data_tests:
              - not_null